### ISSUE TITLE
Upgrade Tracks returning error

### ISSUE THREAD

**Issue by lordlycastle** [abbeycode/AppleScripts#8]
I just tried running `Upgrade Tracks` on iTunes, and I'm getting the following error. 
![screen shot 2016-05-30 at 21 48 51](https://cloud.githubusercontent.com/assets/11729541/15658119/6abec278-26b0-11e6-9efb-7adfb8fc9789.png)
Could you have a look? I tried but couldn't find the problem, thanks for the scripts regardless!

**Comment by abbeycode** [comment]
You were probably cloning tags, right? If so, which tags did you select? I'm guessing the exception happened inside the `tell` block inside the `on CloneTracks` handler. If you run the script through Script Editor, it will hopefully indicate the line on which the exception occurred. I'm guessing "year", since (a) it's sort of a date, (b) it's cast to an integer in the handler I mentioned, and (c) the «class pYr» mentioned in the error could easily mean "Year".

Assuming that's the field giving you issues, did you assign the Year tag with another script? I've definitely cloned that tag successfully in the past, though I haven't done so in the latest couple iTunes versions, so something could indeed have changed.

When debugging iTunes scripts, I usually make a temporary iTunes library, so I don't risk mangling the one I actually care about. There are instruction on how to do so on [an Apple Support page](https://support.apple.com/en-us/HT201596).
